test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cri_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cri_dev
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cri_prod
  pool: 5
  username: cri_prod
  password: d0244bf9
  socket: /tmp/mysql.sock
